FROM golang:1.9.2
MAINTAINER Edward Cheadle

ENV SOURCES /go/src/github.com/echeadle/CLOUD-NATIVE-GO/

COPY . ${SOURCES}

RUN cd ${SOURCES} && GGO_ENABLED=0 go install

ENV PORT 8080
EXPOSE 8080

ENTRYPOINT [ "CLOUD-NATIVE-GO" ]